osx_image: xcode8.3
language: objective-c
cache: cocoapods
podfile: Example/Podfile
before_install:
  - gem install cocoapods
  - pod install --project-directory=Example

script:
- set -o pipefail && xcodebuild test -workspace Example/HairlineConstraint.xcworkspace -scheme HairlineConstraint-Example 'platform=iOS Simulator,name=iPhone 7' ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint
