osx_image: xcode8.3
language: objective-c
cache: cocoapods
podfile: Example/Podfile
before_install:
  - gem install cocoapods@1.2.1
  - pod install --project-directory=Example

script:
- xcodebuild -workspace Example/HairlineConstraint.xcworkspace -scheme HairlineConstraint-Example -sdk iphonesimulator -configuration Debug | xcpretty
- pod lib lint
